docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    
    - run:
        name: task0
        command: cd web && drush -y updb --cache-clear=0
        service: cli
    
    - run:
        name: task1
        command: cd web && drush -y cim
        service: cli
    
    - run:
        name: task2
        command: cd web && drush -y cr
        service: cli
    

environments:
  prod:
    routes:
      - varnish:
        - "2018.midcamp.org" 
        - "midcamp.org" 
        - "www.midcamp.org" 
    cronjobs:
      - name: drush cron
        schedule: "2 * * * *"
        command: drush cron
        service: cli

