docker-compose-yaml: docker-compose.yml
project: midcamp-org

tasks:
  post-rollout:

    - run:
        name: IF no Drupal installed & Pullrequest = Sync database from dev
        command: |
            if [[ -n ${LAGOON_PR_BASE_BRANCH} ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
                drush -y sql-sync @master default
            fi
        service: cli

    - run:
        name: task0
        command: cd web && drush -y updb --cache-clear=0
        service: cli

    - run:
        name: task1
        command: cd web && drush -y cim
        service: cli

    - run:
        name: task2
        command: cd web && drush -y updb --cache-clear=0
        service: cli

    - run:
        name: task3
        command: cd web && drush -y cim
        service: cli

    - run:
        name: task4
        command: cd web && drush -y cr
        service: cli

environments:
  master:
    routes:
      - nginx:
        - "dev.midcamp.org":
            tls-acme: 'false'
            insecure: Redirect
  production:
    routes:
      - varnish:
        - "2018.midcamp.org":
            tls-acme: 'false'
            insecure: Redirect
        - "2019.midcamp.org":
            tls-acme: 'false'
            insecure: Redirect
        - "2020.midcamp.org":
            tls-acme: 'false'
            insecure: Redirect
        - "o.midcamp.org":
            tls-acme: 'false'
            insecure: Redirect
        - "midcamp.org":
            tls-acme: 'false'
            insecure: Redirect
        - "www.midcamp.org":
            tls-acme: 'false'
            insecure: Redirect
    cronjobs:
      - name: drush cron
        schedule: "2 * * * *"
        command: drush cron
        service: cli
