name: midcamp-org
recipe: lagoon
config:
  flavor: drupal
  build:
    - /usr/local/bin/composer install
    - npm install
tooling:
  composer:
    service: cli
    description: Run composer with no memory restrictions
    cmd:
      - php -d memory_limit=-1 /usr/local/bin/composer
  behat:
    service: cli
    description: Run Behat tests
    cmd:
      - /app/vendor/bin/behat
  phpcs:
    service: cli
    cmd:
      - /app/vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
      - /app/vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,info
  phpmd:
    service: cli
    cmd:
      - /app/vendor/bin/phpmd
  get-db:
    service: cli
    description: Import a fresh copy of the production database
    cmd:
      - drush sql-sync @lagoon.midcamp-org-production @self -y
  get-files:
    service: cli
    description: Fetch files (via rsync) from production
    cmd:
      - drush rsync @lagoon.midcamp-org-production:%files @self:%files -y
