FROM amazeeio/php:7.1-cli-drupal

COPY composer.json composer.lock /app/
RUN composer install --prefer-dist --no-dev --no-suggest --optimize-autoloader --apcu-autoloader

COPY . /app

# Define where the Drupal Root is located
ENV WEBROOT=/web
