_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
mode: simple
ignored_config_entities:
  - eventbrite_events.eventbritesettings
  - google_analytics.settings
  - 'mailchimp.settings:api_key'
  - 'mailchimp.settings:connected_id'
  - 'mailchimp.settings:connected_paths'
  - 'recaptcha.settings:secret_key'
  - 'recaptcha.settings:site_key'
  - 'tito.settings:tito_api_token'
