ignored_config_entities:
  0: 'mailchimp.settings:api_key'
  2: 'mailchimp.settings:connected_id'
  4: 'mailchimp.settings:connected_paths'
  6: eventbrite_events.eventbritesettings
  8: google_analytics.settings
  10: 'recaptcha.settings:site_key'
  12: 'recaptcha.settings:secret_key'
  14: 'tito.settings:tito_api_token'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
