_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: false
  user__page:
    menu_name: account
    parent: ''
    weight: -50
    expanded: false
    enabled: true
  user__logout:
    enabled: true
    menu_name: account
    parent: ''
    expanded: false
    weight: -49
  'admin_toolbar_tools__extra_links:node__add':
    weight: 1
    menu_name: admin
    parent: system.admin_content
    enabled: true
    expanded: false
  comment__admin:
    weight: 3
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:view__files':
    weight: 4
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    weight: 5
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
