cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
enable_connected: true
connected_id: 3c32683d2b85c4b
connected_paths: '<front>'
