spt_table:
  -
    status: '1'
    pages: '/2018*'
    theme: bartik
    weight: '-10'
    roles:
      anonymous: 0
      speaker: 0
      content_editor: 0
      administrator: 0
      authenticated: 0
      sponsor: 0
      organizer: 0
    remove: Remove
