# Schema for the configuration files of the midcamp_vbo module.
action.configuration.topic_accept_confirm:
  type: action_configuration_default
  label: 'Accept and confirm topic'
action.configuration.topic_reject:
  type: action_configuration_default
  label: 'Reject and un-confirm topic'