version: 2

jobs:
  build:
    working_directory: /app

    docker:
      - image: drevops/ci-builder
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1

    steps:
      - checkout
      - run:
          name: Build project
          command: |
            composer install --prefer-dist --no-dev --no-suggest --optimize-autoloader --apcu-autoloader --ignore-platform-req=ext-gd
