version: 2

jobs:
  build:
    working_directory: /app

    docker:
      - image: integratedexperts/circleci2-builder
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1

    steps:
      - checkout
      - run:
          name: Set up files
          command: |
            cp .circleci/docker-compose.circleci.yml docker-compose.yml
      - setup_remote_docker
      - run:
          name: Start amazeeio-network
          command: docker network prune -f && docker network inspect amazeeio-network >/dev/null || docker network create amazeeio-network
      - run:
          name: Build project
          command: |
            docker-compose up -d --build
      - run:
          name: Install site
          command: |
            docker-compose exec cli drush site-install --verbose config_installer config_installer_sync_configure_form.sync_directory=../conf/drupal/config/ --yes
      - run:
          name: Install dev dependencies
          command: |
            docker-compose exec cli composer install
      - run:
          name: Run Behat tests
          command: |
            docker-compose exec cli vendor/bin/behat -c behat.circleci.yml
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
