version: 2

jobs:
  build:
    working_directory: /app

    docker:
      - image: drevops/ci-builder
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1

    steps:
      - checkout
      - run:
          name: Set up files
          command: |
            cp .circleci/docker-compose.circleci.yml docker-compose.yml
      - setup_remote_docker
      - run:
          name: Build project
          command: |
            docker-compose up -d --build
