version: 2

jobs:
  build:
    working_directory: /app

    docker:
      - image: drevops/ci-builder
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1

    steps:
      - checkout
      - run:
          name: Set up files
          command: |
            cp .circleci/docker-compose.circleci.yml docker-compose.yml
      - setup_remote_docker
      - run:
          name: Build project
          command: |
            docker-compose up -d --build
      - run:
          name: Install site
          command: |
            docker-compose exec cli drush site-install --verbose config_installer config_installer_sync_configure_form.sync_directory=../conf/drupal/config/ --yes
      - run:
          name: Install dev dependencies
          command: |
            docker-compose exec cli composer install
      - run:
          name: Run Behat tests
          command: |
            docker-compose exec cli vendor/bin/behat -c behat.circleci.yml
