<?php

/**
 * @file
 * Contains midcamp_utility.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function midcamp_utility_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the midcamp_utility module.
    case 'help.page.midcamp_utility':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Misc modifications and helpers') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_pre_view().
 */
function midcamp_utility_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  // Ensure the Event Venue view gets the correct argument when contextual filters not available
  if ($view->id() == 'event_venue') {
    // Ensure we are on a Views page
    $current_route = \Drupal::routeMatch();
    if ($current_route->getParameter('view_id')) {
      // Check the first path part for a value matching an Event term alias.
      $current_uri = \Drupal::request()->getRequestUri();
      $parts = explode('/', $current_uri);
      // Get the term ID from the path
      $term_path = \Drupal::service('path.alias_manager')->getPathByAlias('/' . $parts[1]);
      $term_args = explode('/', $term_path);

      // If we've found a taxonomy term path pass the term ID.
      if ($term_args[1] == 'taxonomy') {
        $tid = end($term_args);
        $view->setArguments([$tid]);
      } else {
        // Otherwise default to the 2019 tid.
        $view->setArguments(['97']);
      }
    }
  }
}
